version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/server/http
    ports:
      - 80:80
      - 443:443
    networks:
      - php-network
    links:
      - php
      - mysql
      - rabbitmq
  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/server/http
    ports:
      - 9000:9000
    networks:
      - php-network
    links:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:${DB_VERSION}
    restart: unless-stopped
    hostname: ${DB_HOST}
    container_name: mysql_dh

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/server/http
    ports:
      - 3306:3306
    networks:
      - php-network

  swagger-ui:
    environment:
    - SWAGGER_JSON=/swagger.yaml
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    volumes:
      - ./resources/swagger/swagger.yaml:/swagger.yaml
    ports:
      - 8080:8080
    networks:
      - php-network

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: unless-stopped
    hostname: ${AMQP_HOST}
    container_name: rabbit_dh
    environment:
      RABBITMQ_ERLANG_COOKIE: ${ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASS}
      RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - php-network
    tty: true
    command:  bash -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server;"

networks:
  php-network:
    driver: bridge
