openapi: 3.0.0
info:
  description: This is a sample server.
  version: 1.0.0
  title: Swagger DH
  contact:
    email: themobi@hotmail.com
servers:
  - url: '{protocol}://localhost:{port}/{apipath}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      port:
        enum:
          - '82'
          - '8000'
        default: '82'
      apipath:
        enum:
          - 'api/v1'
        default: 'api/v1'
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    post:
      tags:
        - user
      summary: Add a new user
      description: ''
      operationId: 'adduser'
      requestBody:
        $ref: '#/components/requestBodies/UserAdd'
      responses:
        '200':
          description: OK
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              example: 'success'
          headers:
            Access-Control-Allow-Origin:
              description: The cors
              schema:
                type: string
components:
  schemas:
    Users:
      required:
        - id
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      type: object
  requestBodies:
    UserAdd:
      description: 'User object'
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/Users'
